import { AboutSlint, Button, VerticalBox, LineEdit, StandardListView, GroupBox } from "std-widgets.slint";

export component HelloWorld inherits Window {
    callback run-rom(string);
    in property <string> results: "";

    VerticalBox {
        alignment: start;
        Text {
            text: "Rusty CHIP-8";
            font-size: 24px;
            horizontal-alignment: center;
        }
        // AboutSlint {
        //     preferred-height: 150px;
        // }
        HorizontalLayout {
            alignment: center;
            input := LineEdit {
                placeholder-text: "Enter your number";
                font-size: 16px;
                height: 35px;
                horizontal-alignment: center;
            }
            Button {
                text: "OK!";
                clicked => {
                    root.run-rom(input.text);
                }
            }
        }
    }
}